In [250]:
import numpy as np
from numpy.random import randn
from pandas import Series

# NumPy数据类型体系

In [3]:
ints = np.ones(10, dtype=np.uint16)

In [4]:
floats = np.ones(10, dtype=np.float32)

In [5]:
np.issubdtype(ints.dtype, np.integer)

True

In [6]:
np.issubdtype(floats.dtype, np.floating)

True

In [7]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

# 高级数组操作

In [8]:
arr = np.arange(8)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
arr = np.arange(15)

In [49]:
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
other_arr = np.ones((3,5))

In [15]:
other_arr.shape

(3, 5)

In [16]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
arr = np.arange(15).reshape((5,3))

In [22]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr  = np.arange(12).reshape((3,4))

In [25]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [61]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [62]:
arr1.shape

(2, 3)

In [63]:
arr2 = np.array([[7,8,9],[10,11,12]])

In [64]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [65]:
np.concatenate([arr1,arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
np.concatenate([arr1,arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [34]:
arr = randn(5,2)
arr

array([[ 0.47189605,  0.12010199],
       [ 0.19715678, -0.97376394],
       [-1.13769327,  0.44031614],
       [-0.12704464, -1.49035631],
       [-0.43110692,  0.76670471]])

In [36]:
first,second,third = np.split(arr,[1,3])
print first
print 
print second
print
print third

[[0.47189605 0.12010199]]

[[ 0.19715678 -0.97376394]
 [-1.13769327  0.44031614]]

[[-0.12704464 -1.49035631]
 [-0.43110692  0.76670471]]


In [37]:
arr = np.arange(6)

In [38]:
arr1 = arr.reshape((3,2))

In [39]:
arr2 = randn(3,2)

In [40]:
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 2.66111327, -1.64589725],
       [-0.64369352, -1.72256023],
       [ 0.40952289, -1.23820066]])

In [41]:
np.c_[np.r_[arr1,arr2],arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 2.66111327, -1.64589725,  3.        ],
       [-0.64369352, -1.72256023,  4.        ],
       [ 0.40952289, -1.23820066,  5.        ]])

In [42]:
np.c_[1:6,-10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

## 元素的重复操作:tile和repeat

In [67]:
arr = np.arange(3)

In [68]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [69]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [87]:
arr = randn(2,2)

In [89]:
arr

array([[-0.97136108, -0.08217484],
       [ 0.00513383, -0.19369607]])

In [88]:
arr.repeat(2)

array([-0.97136108, -0.97136108, -0.08217484, -0.08217484,  0.00513383,
        0.00513383, -0.19369607, -0.19369607])

In [81]:
arr.repeat([2,3], axis=0)

array([[-0.13958782, -1.09051068],
       [-0.13958782, -1.09051068],
       [-0.66308408, -0.26026079],
       [-0.66308408, -0.26026079],
       [-0.66308408, -0.26026079]])

In [86]:
arr.repeat([2,3], axis=1)

array([[ 1.42449044,  1.42449044, -1.0717589 , -1.0717589 , -1.0717589 ],
       [ 0.40709526,  0.40709526,  0.50563754,  0.50563754,  0.50563754]])

In [90]:
np.tile(arr,2)

array([[-0.97136108, -0.08217484, -0.97136108, -0.08217484],
       [ 0.00513383, -0.19369607,  0.00513383, -0.19369607]])

In [93]:
np.hstack((arr,arr))

array([[-0.97136108, -0.08217484, -0.97136108, -0.08217484],
       [ 0.00513383, -0.19369607,  0.00513383, -0.19369607]])

In [77]:
np.tile(arr,(2,1))

array([[-2.62012354,  0.78747234],
       [-1.31688785, -0.68522845],
       [-2.62012354,  0.78747234],
       [-1.31688785, -0.68522845]])

In [78]:
np.tile(arr,(3,2))

array([[-2.62012354,  0.78747234, -2.62012354,  0.78747234],
       [-1.31688785, -0.68522845, -1.31688785, -0.68522845],
       [-2.62012354,  0.78747234, -2.62012354,  0.78747234],
       [-1.31688785, -0.68522845, -1.31688785, -0.68522845],
       [-2.62012354,  0.78747234, -2.62012354,  0.78747234],
       [-1.31688785, -0.68522845, -1.31688785, -0.68522845]])

## 花式索引的等价函数:take和put

In [107]:
arr = np.arange(10)*100

In [108]:
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [109]:
inds = [7,1,2,6]

In [110]:
arr[inds]

array([700, 100, 200, 600])

In [97]:
arr.take(inds)

array([700, 100, 200, 600])

In [98]:
arr.put(inds, 43)

In [99]:
arr

array([  0,  43,  43, 300, 400, 500,  43,  43, 800, 900])

In [100]:
arr.put(inds, [40,41,42,43])

In [101]:
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [102]:
inds = [2,0,2,1]

In [103]:
arr = randn(2,4)

In [104]:
arr

array([[-0.57854901,  0.26067262, -0.56442368, -1.36368674],
       [ 1.92943585, -1.1349965 ,  0.39843584, -0.55541664]])

In [105]:
arr.take(inds, axis=1)

array([[-0.56442368, -0.57854901, -0.56442368,  0.26067262],
       [ 0.39843584,  1.92943585,  0.39843584, -1.1349965 ]])

# 广播

In [111]:
arr = np.arange(5)

In [112]:
arr

array([0, 1, 2, 3, 4])

In [113]:
arr*4

array([ 0,  4,  8, 12, 16])

In [114]:
arr =randn(4,3)

In [146]:
arr.mean(0).shape

(3,)

In [116]:
demeaned = arr - arr.mean(0)

In [117]:
demeaned

array([[-1.42232519, -1.94148256, -0.37768964],
       [ 0.94015402,  0.78618845, -0.00904147],
       [-0.00241891,  0.9171878 , -0.82022364],
       [ 0.48459008,  0.23810631,  1.20695475]])

In [118]:
demeaned.mean(0)

array([-1.11022302e-16,  5.55111512e-17,  0.00000000e+00])

In [119]:
arr

array([[-2.32736375, -2.4352045 , -1.0108825 ],
       [ 0.03511547,  0.29246651, -0.64223433],
       [-0.90745747,  0.42346586, -1.4534165 ],
       [-0.42044847, -0.25561563,  0.57376189]])

In [150]:
row_means = arr.mean(1)

In [151]:
row_means.shape

(4,)

In [121]:
row_means.reshape((4,1))

array([[-1.92448358],
       [-0.10488412],
       [-0.6458027 ],
       [-0.03410074]])

In [122]:
demeaned = arr - row_means.reshape((4,1))

In [123]:
demeaned.mean(1)

array([ 1.48029737e-16,  0.00000000e+00, -3.70074342e-17,  0.00000000e+00])

In [124]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [125]:
arr-arr.mean(1).reshape((4,1))

array([[-0.40288017, -0.51072091,  0.91360108],
       [ 0.13999959,  0.39735063, -0.53735022],
       [-0.26165476,  1.06926856, -0.80761379],
       [-0.38634773, -0.22151489,  0.60786263]])

In [126]:
arr = np.zeros((4,4))

In [127]:
arr_3d = arr[:, np.newaxis, :]

In [128]:
arr_3d.shape

(4, 1, 4)

In [129]:
arr_1d = np.random.normal(size=3)

In [130]:
arr_1d[:,np.newaxis]

array([[ 0.21838779],
       [ 0.14016242],
       [-1.77306832]])

In [152]:
arr_1d[np.newaxis, :]

array([[ 0.21838779,  0.14016242, -1.77306832]])

In [132]:
arr = randn(3,4,5)

In [133]:
depth_means = arr.mean(2)

In [134]:
depth_means

array([[-0.13486208, -0.12560904, -0.06246225, -0.13994619],
       [-0.13740794,  0.05673512,  0.64430378,  0.36189669],
       [-0.06079213,  0.60862843,  0.15738857, -0.5187356 ]])

In [135]:
demeaned = arr-depth_means[:, :, np.newaxis]

In [136]:
demeaned.mean(2)

array([[ 4.44089210e-17,  0.00000000e+00,  4.44089210e-17,
         0.00000000e+00],
       [-2.22044605e-17,  1.11022302e-17, -4.44089210e-17,
         8.88178420e-17],
       [-1.11022302e-17, -8.88178420e-17,  0.00000000e+00,
        -8.88178420e-17]])

In [137]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr-means[indexer]

## 通过广播设置数组的值

In [138]:
arr = np.zeros((4,3))

In [139]:
arr[:] = 5

In [140]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [141]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [142]:
arr[:] = col[:, np.newaxis]

In [143]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [144]:
arr[:2] = [[-1.37],[0.509]]

In [145]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

# ufunc高级应用

In [153]:
arr = np.arange(10)

In [154]:
np.add.reduce(arr)

45

In [155]:
arr.sum()

45

In [156]:
arr = randn(5,5)

In [157]:
arr[::2].sort(1)

In [158]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

In [159]:
np.logical_and.reduce(arr[:, :-1]<arr[:,1:], axis=1)

array([ True, False,  True, False,  True])

In [160]:
arr = np.arange(15).reshape((3,5))

In [161]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [162]:
arr=np.arange(3).repeat([1,2,2])

In [163]:
arr

array([0, 1, 1, 2, 2])

In [164]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [165]:
result = np.subtract.outer(randn(3,4), randn(5))

In [166]:
result.shape

(3, 4, 5)

In [167]:
arr = np.arange(10)

In [168]:
np.add.reduceat(arr, [0,5,8])

array([10, 18, 17])

In [184]:
arr = np.multiply.outer(np.arange(4), np.arange(5))

In [185]:
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [186]:
np.add.reduceat(arr, [0,2,4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

In [187]:
np.add.reduceat(arr, [0,2,3], axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

## 自定义ufunc

In [172]:
def add_elements(x,y):
    return x+y

In [175]:
add_them = np.frompyfunc(add_elements, 2,1)

In [176]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [177]:
add_them = np.vectorize(add_elements, otypes=[np.float64])

In [178]:
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [179]:
arr = randn(10000)

In [180]:
%timeit add_them(arr, arr)

100 loops, best of 3: 1.87 ms per loop


In [181]:
%timeit np.add(arr, arr)

The slowest run took 16.78 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.83 µs per loop


# 结构化和记录式数组

In [188]:
dtype = [('x', np.float64), ('y', np.int32)]

In [189]:
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)

In [191]:
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [192]:
sarr[0]

(1.5, 6)

In [193]:
sarr[0]['y']

6

In [194]:
sarr['x']

array([1.5       , 3.14159265])

In [195]:
dtype = [('x',np.int64, 3), ('y', np.int32)]

In [196]:
arr = np.zeros(3, dtype=dtype)

In [197]:
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [198]:
arr[0]['x']

array([0, 0, 0])

In [201]:
dtype = [('x',[('a','f8'),('b','f4')]), ('y',np.int32)]

In [202]:
data = np.array([((1,2), 5), ((3,4),6)], dtype=dtype)

In [203]:
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [204]:
data['y']

array([5, 6], dtype=int32)

In [205]:
data['x']['a']

array([1., 3.])

# 更多有关排序的话题

In [206]:
arr = randn(6)

In [207]:
arr.sort()

In [208]:
arr

array([-1.68227937e+00, -1.67684062e+00, -9.04882425e-01, -1.02171851e-01,
       -9.54613782e-04,  1.52129413e+00])

In [209]:
arr = randn(3,5)

In [210]:
arr

array([[-0.1210841 , -0.41633303,  0.23432578,  0.57063909,  1.1153875 ],
       [ 0.3824108 , -0.53258719,  0.60029483,  0.00903923, -0.55550751],
       [-1.59575629,  0.66817082, -0.07412347, -0.25784968, -0.80306284]])

In [211]:
arr[:, 0].sort()

In [212]:
arr

array([[-1.59575629, -0.41633303,  0.23432578,  0.57063909,  1.1153875 ],
       [-0.1210841 , -0.53258719,  0.60029483,  0.00903923, -0.55550751],
       [ 0.3824108 ,  0.66817082, -0.07412347, -0.25784968, -0.80306284]])

In [213]:
arr = randn(5)

In [214]:
arr

array([-0.13227481,  0.11143738, -2.39015219, -1.61109127,  0.08146375])

In [215]:
np.sort(arr)

array([-2.39015219, -1.61109127, -0.13227481,  0.08146375,  0.11143738])

In [216]:
arr

array([-0.13227481,  0.11143738, -2.39015219, -1.61109127,  0.08146375])

In [217]:
arr = randn(3,5)

In [218]:
arr

array([[ 1.10948166,  0.59036611, -0.21860507,  0.98604794,  1.26939549],
       [ 1.38372128, -1.23666804,  1.28638799,  0.680961  ,  0.54011376],
       [-0.01115602,  1.11823501, -0.71519065, -0.11150965, -0.3135234 ]])

In [219]:
arr.sort(axis=1)

In [220]:
arr

array([[-0.21860507,  0.59036611,  0.98604794,  1.10948166,  1.26939549],
       [-1.23666804,  0.54011376,  0.680961  ,  1.28638799,  1.38372128],
       [-0.71519065, -0.3135234 , -0.11150965, -0.01115602,  1.11823501]])

In [221]:
arr[:, ::-1]

array([[ 1.26939549,  1.10948166,  0.98604794,  0.59036611, -0.21860507],
       [ 1.38372128,  1.28638799,  0.680961  ,  0.54011376, -1.23666804],
       [ 1.11823501, -0.01115602, -0.11150965, -0.3135234 , -0.71519065]])

## 间接排序:argsort和lexsort

In [222]:
values = np.array([5,0,1,3,2])

In [223]:
indexer = values.argsort()

In [224]:
indexer

array([1, 2, 4, 3, 0])

In [225]:
values[indexer]

array([0, 1, 2, 3, 5])

In [226]:
arr = randn(3,5)

In [228]:
arr[0] = values

In [229]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.37748529, -0.66499636, -0.90452037,  0.24440893,  0.83314253],
       [ 0.36003673, -0.0661077 , -1.22395305,  1.5982917 ,  0.44216561]])

In [230]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.66499636, -0.90452037,  0.83314253,  0.24440893, -0.37748529],
       [-0.0661077 , -1.22395305,  0.44216561,  1.5982917 ,  0.36003673]])

In [231]:
first_name = np.array(['Bob','Jane','Steve','Bill','Barbara'])
last_name = np.array(['Jones','Arnold','Arnold','Jones','Walters'])
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

In [248]:
sorter

array([1, 2, 3, 0, 4])

## 其他排序算法

In [232]:
values = np.array(['2:first','2:second','1:first','1:second','1:third'])

In [233]:
key = np.array([2,2,1,1,1])

In [234]:
indexer = key.argsort(kind='mergesort')

In [235]:
indexer

array([2, 3, 4, 0, 1])

In [236]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='|S8')

In [237]:
arr = np.array([0,1,7,12,15])

In [238]:
arr.searchsorted(9)

3

In [239]:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5])

In [240]:
arr = np.array([0,0,0,1,1,1,1])

In [241]:
arr.searchsorted([0,1])

array([0, 3])

In [242]:
arr.searchsorted([0,1], side='right')

array([3, 7])

In [243]:
data = np.floor(np.random.uniform(0,10000,size=50))

In [244]:
bins = np.array([0,100,1000,5000,10000])

In [245]:
data

array([2702., 2587., 2425., 8408., 7413., 3891., 5118., 8625., 1280.,
       7512., 3012., 2958., 6295., 5385., 6264., 7005., 1734., 7997.,
       3980., 8084., 4674., 2916., 7549., 6829., 8319.,  573., 8346.,
       4152., 8797., 2233., 8013., 7424., 3516., 5385., 9149., 6549.,
       5499., 7206., 2087., 7839., 1589., 2605., 7175., 9514., 7316.,
       4529., 5016., 8453., 5536., 6190.])

In [246]:
labels = bins.searchsorted(data)

In [247]:
labels

array([3, 3, 3, 4, 4, 3, 4, 4, 3, 4, 3, 3, 4, 4, 4, 4, 3, 4, 3, 4, 3, 3,
       4, 4, 4, 2, 4, 3, 4, 3, 4, 4, 3, 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 4,
       4, 3, 4, 4, 4, 4])

In [251]:
Series(data).groupby(labels).mean()

2     573.000000
3    2937.222222
4    7232.580645
dtype: float64

In [252]:
np.digitize(data, bins)

array([3, 3, 3, 4, 4, 3, 4, 4, 3, 4, 3, 3, 4, 4, 4, 4, 3, 4, 3, 4, 3, 3,
       4, 4, 4, 2, 4, 3, 4, 3, 4, 4, 3, 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 4,
       4, 3, 4, 4, 4, 4])

# NumPy的matrix类

In [253]:
X = np.array([[8,3,-1,2],
             [3,6,0,2]])

In [254]:
X[:,0]

array([8, 3])

In [255]:
y = X[:, :1]

In [256]:
X

array([[ 8,  3, -1,  2],
       [ 3,  6,  0,  2]])

In [257]:
y

array([[8],
       [3]])

# 高级数组输入输出

In [259]:
mmap = np.memmap('mymmp', dtype='float64', mode='w+', shape=(10000,10000))

In [260]:
mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [261]:
section = mmap[:5]

In [262]:
section[:] = np.random.randn(5,10000)

In [263]:
mmap.flush()

In [264]:
mmap

memmap([[-2.94325404e-01,  1.69720158e-02, -7.13181099e-01, ...,
         -1.60429082e-01, -1.70160750e+00, -1.14589203e+00],
        [-8.97697959e-01,  9.54922877e-01,  1.42272712e+00, ...,
         -1.52031711e-03, -6.19130545e-01,  3.67646486e-03],
        [ 1.72801633e+00, -1.45815562e+00, -1.14898894e+00, ...,
         -2.81983515e-01, -5.76933426e-01, -1.46584385e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [265]:
del mmap

In [268]:
mmap = np.memmap('mymmp', dtype='float64', shape=(10000,10000))

In [269]:
mmap

memmap([[-2.94325404e-01,  1.69720158e-02, -7.13181099e-01, ...,
         -1.60429082e-01, -1.70160750e+00, -1.14589203e+00],
        [-8.97697959e-01,  9.54922877e-01,  1.42272712e+00, ...,
         -1.52031711e-03, -6.19130545e-01,  3.67646486e-03],
        [ 1.72801633e+00, -1.45815562e+00, -1.14898894e+00, ...,
         -2.81983515e-01, -5.76933426e-01, -1.46584385e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])