# 合并数据集

## 数据库风格的DataFrame合并

In [1]:
from pandas import DataFrame, Series
import pandas as pd
import numpy as np

In [2]:
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],
               'data1':range(7)})
df2 = DataFrame({'key':['a','b','d'],'data2':range(3)})

In [3]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [4]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [5]:
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
df1 = DataFrame({'key1':['b','b','a','c','a','a','b'],
                 'key2':['1','2','4','d','5','3','6'],
               'data1':range(7)})
df2 = DataFrame({'key1':['a','b','d'],'data2':range(3),'key2':['5','2','9']})
pd.merge(df1,df2)

data1 key1 key2  data2
0      1    b    2      1
1      4    a    5      0

In [9]:
pd.merge(df1, df2, on='key1')

data1 key1 key2_x  data2 key2_y
0      0    b      1      1      2
1      1    b      2      1      2
2      6    b      6      1      2
3      2    a      4      0      5
4      4    a      5      0      5
5      5    a      3      0      5

In [10]:
df3 = DataFrame({'1key':['b','b','a','c','a','a','b'],
                'data1':range(7)})
df4 = DataFrame({'rkey':['a','b','d'],
                'data2':range(3)})

In [11]:
pd.merge(df3, df4, left_on='1key', right_on='rkey')

1key  data1  data2 rkey
0    b      0      1    b
1    b      1      1    b
2    b      6      1    b
3    a      2      0    a
4    a      4      0    a
5    a      5      0    a

In [12]:
pd.merge(df1,df2, how='outer')

data1 key1 key2  data2
0    0.0    b    1    NaN
1    1.0    b    2    1.0
2    2.0    a    4    NaN
3    3.0    c    d    NaN
4    4.0    a    5    0.0
5    5.0    a    3    NaN
6    6.0    b    6    NaN
7    NaN    d    9    2.0

In [13]:
df1 = DataFrame({'key':['b','b','a','c','a','b'],
                'data1':range(6)})
df2 = DataFrame({'key':['a','b','a','b','d'],
                'data2':range(5)})

In [14]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [15]:
pd.merge(df1,df2,on='key',how='left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [17]:
pd.merge(df1, df2, how='inner')

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [18]:
left = DataFrame({'key1':['foo','foo','bar'],
                 'key2':['one','two','one'],
                 'lval':[1,2,3]})
right = DataFrame({'key1':['foo','foo','bar','bar'],
                  'key2':['one','one','one','two'],
                  'rval':[4,5,6,7]})

In [19]:
pd.merge(left, right, on=['key1','key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [21]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [22]:
pd.merge(left, right,on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

## 索引上的合并

In [50]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],
                  'value':range(6)})
right1 =DataFrame({'group_val':[2.5,7]}, index=['a','b'])

In [40]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [41]:
right1

group_val
a        2.5
b        7.0

In [42]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        2.5
2   a      2        2.5
3   a      3        2.5
1   b      1        7.0
4   b      4        7.0

In [43]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        2.5
2   a      2        2.5
3   a      3        2.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [45]:
right1.index.name = 'key'

In [48]:
right2 = right1.reset_index()

In [49]:
right2

key  group_val
0   a        2.5
1   b        7.0

In [51]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        2.5
2   a      2        2.5
3   a      3        2.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [52]:
lefth = DataFrame({'key1':['Ohio', 'Ohio','Ohio', 'Nevada','Nevada'],
                  'key2':[2000,2001,2002,2001,2002],
                  'data':np.arange(5.)})

In [53]:
righth = DataFrame(np.arange(12).reshape((6,2)),
                  index=[['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],
                        [2001,2000,2000,2000,2001,2002]],
                  columns = ['event1','event2'])

In [54]:
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [55]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [56]:
pd.merge(lefth, righth, left_on=['key1','key2'], right_index=True)

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

In [60]:
left2 = DataFrame([[1,2],[3,4],[5,6]],index=['a','c','e'],columns=['Ohio','Nevada'])
right2 = DataFrame([[7,8],[9,10],[11,12],[13,14]],index=['b','c','d','e'],columns=['Missouri','Alabama'])

In [61]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [62]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [63]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [64]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [66]:
left1.join(right1,on='key')

key  value  group_val
0   a      0        2.5
1   b      1        7.0
2   a      2        2.5
3   a      3        2.5
4   b      4        7.0
5   c      5        NaN

In [67]:
another = DataFrame([[7,8],[9,10],[11,12],[16,17]],index=['a','c','e','f'], columns=['New York', 'Oregon'])

In [72]:
right2.join([left2, another])

Missouri  Alabama  Ohio  Nevada  New York  Oregon
b         7        8   NaN     NaN       NaN     NaN
c         9       10   3.0     4.0       9.0    10.0
d        11       12   NaN     NaN       NaN     NaN
e        13       14   5.0     6.0      11.0    12.0

In [69]:
left2.join([right2, another], how='outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

In [70]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [71]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

## 轴向连接

In [3]:
arr = np.arange(12).reshape((3,4))

In [4]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.concatenate([arr,arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [6]:
s1 = Series([0,1], index=['a','b'])

In [7]:
s2 = Series([2,3,4], index=['c','d','e'])

In [8]:
s3 = Series([5,6], index=['f','g'])

In [9]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [11]:
pd.concat([s1,s2,s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [12]:
s4 = pd.concat([s1*5, s3])

In [13]:
pd.concat([s1,s4], axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [14]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [15]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [16]:
result = pd.concat([s1,s1,s3], keys=['one','two','three'])

In [17]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [18]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [19]:
pd.concat([s1,s2,s3],axis=1, keys=['one','two','three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [20]:
df1 = DataFrame(np.arange(6).reshape(3,2), index=['a','b','c'], columns=['one','two'])

In [21]:
df2 = DataFrame(5+np.arange(4).reshape(2,2), index=['a','c'], columns=['three','four'])

In [22]:
pd.concat([df1,df2], axis=1, keys=['level1','level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [23]:
pd.concat({'level1':df1,'level2':df2}, axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [24]:
pd.concat([df1,df2], axis=1, keys=['level1','level2'], names=['upper','lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [25]:
df1 = DataFrame(np.random.randn(3,4), columns=['a','b','c','d'])

In [26]:
df2 = DataFrame(np.random.randn(2,3), columns=['b','d','a'])

In [27]:
pd.concat([df1,df2], ignore_index=True)

a         b         c         d
0 -0.765945 -0.864303  1.444483  0.978313
1  1.397102  0.279107 -0.402417 -0.030659
2  0.885728  0.109959  0.564856  0.346239
3 -0.213772 -0.966065       NaN  0.053911
4  0.796836  0.660568       NaN  0.604178

## 合并重叠数据

In [3]:
a = Series([np.nan,2.5,np.nan,3.5,4.5,np.nan], index=['f','e','d','c','b','a'])

In [4]:
b = Series(np.arange(len(a), dtype=np.float64), index=['f','e','d','c','b','a'])

In [5]:
b[-1] = np.nan

In [6]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [7]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [8]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [9]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [10]:
df1 = DataFrame({'a':[1,np.nan,5,np.nan],
                'b':[np.nan,2,np.nan,6],
                'c':range(2,18,4)})
df2 = DataFrame({'a':[5,4,np.nan,3,7],
                'b':[np.nan, 3,4,6,8]})

In [11]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

# 重塑和轴向旋转

In [12]:
data = DataFrame(np.arange(6).reshape((2,3)),
                index=pd.Index(['Ohio','Colorado'], name='state'),
                columns=pd.Index(['one','two','three'],name='number'))

In [13]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [14]:
result = data.stack()

In [15]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [16]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [17]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [18]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [19]:
s1 = Series([0,1,2,3], index=['a','b','c','d'])

In [20]:
s2 = Series([4,5,6], index=['c','d','e'])

In [21]:
data2 = pd.concat([s1,s2], keys=['one', 'two'])

In [22]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [23]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [24]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [25]:
df = DataFrame({'left':result, 'right':result+5},
              columns=pd.Index(['left','right'], name='side'))

In [26]:
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [27]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [28]:
df.unstack('state').stack('side')

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

## 将长格式旋转为宽格式

# 数据转换

## 移除重复数据

In [30]:
data = DataFrame({'k1':['one']*3+['two']*4,
                 'k2':[1,1,2,3,3,4,4]})

In [31]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [32]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [34]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [35]:
data['v1'] = range(7)

In [36]:
data

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [37]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [41]:
data.drop_duplicates(['k1','k2'], keep='last')

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

## 利用函数或映射进行数据转换

In [42]:
data = DataFrame({'food':['bacon','pulled pork','bacon','Pastrami',
                         'corned beef', 'Bacon','pastrami','honey ham','nova lox'],
                 'ounces':[4,3,12,6,7,8,3,5,6]})

In [43]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [44]:
data

food  ounces
0        bacon       4
1  pulled pork       3
2        bacon      12
3     Pastrami       6
4  corned beef       7
5        Bacon       8
6     pastrami       3
7    honey ham       5
8     nova lox       6

In [45]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [46]:
data

food  ounces  animal
0        bacon       4     pig
1  pulled pork       3     pig
2        bacon      12     pig
3     Pastrami       6     cow
4  corned beef       7     cow
5        Bacon       8     pig
6     pastrami       3     cow
7    honey ham       5     pig
8     nova lox       6  salmon

In [47]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

## 值替换

In [48]:
data = Series([1,-999,2,-999,-1000,3])

In [49]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [50]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [51]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [52]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## 重命名轴索引

In [53]:
data = DataFrame(np.arange(12).reshape((3,4)),
                index=['Ohio','Colorado','New York'],
                columns=['one','two','three','four'])

In [54]:
data.index.map(str.upper)

Index([u'OHIO', u'COLORADO', u'NEW YORK'], dtype='object')

In [55]:
data.index=data.index.map(str.upper)

In [56]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [57]:
data.rename(index={'OHIO':'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [58]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [59]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

## 离散化和面元划分

In [60]:
ages =[20,22,25,27,21,23,37,32,61,45,41,32]

In [61]:
bins = [18,25,35,60,100]

In [62]:
cats = pd.cut(ages, bins)

In [63]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [64]:
cats.labels

/home/parallels/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [65]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [69]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [70]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [71]:
pd.cut(ages, [18,26,36,61,100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [72]:
group_names = ['Youth', 'YoungAdult','MiddleAges','Senior']

In [78]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAges, MiddleAges, YoungAdult]
Length: 12
Categories (4, object): [MiddleAges < Senior < YoungAdult < Youth]

In [79]:
data = np.random.rand(20)

In [80]:
pd.cut(data, 4, precision=2)

[(0.77, 0.99], (0.12, 0.34], (0.56, 0.77], (0.56, 0.77], (0.77, 0.99], ..., (0.77, 0.99], (0.56, 0.77], (0.12, 0.34], (0.77, 0.99], (0.56, 0.77]]
Length: 20
Categories (4, interval[float64]): [(0.12, 0.34] < (0.34, 0.56] < (0.56, 0.77] < (0.77, 0.99]]

In [81]:
data = np.random.randn(1000)

In [82]:
cats = pd.qcut(data, 4)

In [83]:
cats

[(0.0455, 0.643], (0.643, 3.93], (0.643, 3.93], (-0.64, 0.0455], (0.0455, 0.643], ..., (-3.3129999999999997, -0.64], (0.0455, 0.643], (-0.64, 0.0455], (0.0455, 0.643], (-3.3129999999999997, -0.64]]
Length: 1000
Categories (4, interval[float64]): [(-3.3129999999999997, -0.64] < (-0.64, 0.0455] < (0.0455, 0.643] < (0.643, 3.93]]

In [84]:
pd.value_counts(cats)

(0.643, 3.93]                   250
(0.0455, 0.643]                 250
(-0.64, 0.0455]                 250
(-3.3129999999999997, -0.64]    250
dtype: int64

In [85]:
pd.qcut(data, [0,0.1,0.5,0.9,1])

[(0.0455, 1.308], (0.0455, 1.308], (1.308, 3.93], (-1.193, 0.0455], (0.0455, 1.308], ..., (-3.3129999999999997, -1.193], (0.0455, 1.308], (-1.193, 0.0455], (0.0455, 1.308], (-1.193, 0.0455]]
Length: 1000
Categories (4, interval[float64]): [(-3.3129999999999997, -1.193] < (-1.193, 0.0455] < (0.0455, 1.308] < (1.308, 3.93]]

## 检测和过滤异常值

In [86]:
np.random.seed(12345)
data = DataFrame(np.random.randn(1000,4))

In [87]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [88]:
col = data[3]

In [89]:
col[np.abs(col)>3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [105]:
data[(np.abs(np.abs(data)-3) < 1.0e-9).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.000000 -1.021228
97  -0.774363  0.552936  0.106061  3.000000
102 -0.655054 -0.565230  3.000000  0.959533
305 -2.315555  0.457246 -0.025907 -3.000000
324  0.050188  1.951312  3.000000  0.963301
400  0.146326  0.508391 -0.196713 -3.000000
499 -0.293333 -0.242459 -3.000000  1.918403
523 -3.000000 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.000000  1.369891
808 -0.362528 -3.000000  1.553205 -2.186301
900  3.000000 -2.372214  0.851010  1.332846

In [108]:
data[np.abs(np.abs(data)-3) > 1.0e-1] = np.sign(data)*3

0   1   2   3
0   NaN NaN NaN NaN
1   NaN NaN NaN NaN
2   NaN NaN NaN NaN
3   NaN NaN NaN NaN
4   NaN NaN NaN NaN
5   NaN NaN NaN NaN
6   NaN NaN NaN NaN
7   NaN NaN NaN NaN
8   NaN NaN NaN NaN
9   NaN NaN NaN NaN
10  NaN NaN NaN NaN
11  NaN NaN NaN NaN
12  NaN NaN NaN NaN
13  NaN NaN NaN NaN
14  NaN NaN NaN NaN
15  NaN NaN NaN NaN
16  NaN NaN NaN NaN
17  NaN NaN NaN NaN
18  NaN NaN NaN NaN
19  NaN NaN NaN NaN
20  NaN NaN NaN NaN
21  NaN NaN NaN NaN
22  NaN NaN NaN NaN
23  NaN NaN NaN NaN
24  NaN NaN NaN NaN
25  NaN NaN NaN NaN
26  NaN NaN NaN NaN
27  NaN NaN NaN NaN
28  NaN NaN NaN NaN
29  NaN NaN NaN NaN
..   ..  ..  ..  ..
970 NaN NaN NaN NaN
971 NaN NaN NaN NaN
972 NaN NaN NaN NaN
973 NaN NaN NaN NaN
974 NaN NaN NaN NaN
975 NaN NaN NaN NaN
976 NaN NaN NaN NaN
977 NaN NaN NaN NaN
978 NaN NaN NaN NaN
979 NaN NaN NaN NaN
980 NaN NaN NaN NaN
981 NaN NaN NaN NaN
982 NaN NaN NaN NaN
983 NaN NaN NaN NaN
984 NaN NaN NaN NaN
985 NaN NaN NaN NaN
986 NaN NaN NaN NaN
987 NaN NaN NaN NaN
988 NaN NaN NaN NaN
989 NaN NaN NaN NaN
990 NaN NaN NaN NaN
991 NaN NaN NaN NaN
992 NaN NaN NaN NaN
993 NaN NaN NaN NaN
994 NaN NaN NaN NaN
995 NaN NaN NaN NaN
996 NaN NaN NaN NaN
997 NaN NaN NaN NaN
998 NaN NaN NaN NaN
999 NaN NaN NaN NaN

[1000 rows x 4 columns]

In [96]:
(np.sign(data)*3).shape

(1000, 4)

In [103]:
np.abs(np.abs(data)-3) < 1.0e-9

0      1      2      3
0    False  False  False  False
1    False  False  False  False
2    False  False  False  False
3    False  False  False  False
4    False  False  False  False
5    False  False   True  False
6    False  False  False  False
7    False  False  False  False
8    False  False  False  False
9    False  False  False  False
10   False  False  False  False
11   False  False  False  False
12   False  False  False  False
13   False  False  False  False
14   False  False  False  False
15   False  False  False  False
16   False  False  False  False
17   False  False  False  False
18   False  False  False  False
19   False  False  False  False
20   False  False  False  False
21   False  False  False  False
22   False  False  False  False
23   False  False  False  False
24   False  False  False  False
25   False  False  False  False
26   False  False  False  False
27   False  False  False  False
28   False  False  False  False
29   False  False  False  False
..     ...    ...    ...    ...
970  False  False  False  False
971  False  False  False  False
972  False  False  False  False
973  False  False  False  False
974  False  False  False  False
975  False  False  False  False
976  False  False  False  False
977  False  False  False  False
978  False  False  False  False
979  False  False  False  False
980  False  False  False  False
981  False  False  False  False
982  False  False  False  False
983  False  False  False  False
984  False  False  False  False
985  False  False  False  False
986  False  False  False  False
987  False  False  False  False
988  False  False  False  False
989  False  False  False  False
990  False  False  False  False
991  False  False  False  False
992  False  False  False  False
993  False  False  False  False
994  False  False  False  False
995  False  False  False  False
996  False  False  False  False
997  False  False  False  False
998  False  False  False  False
999  False  False  False  False

[1000 rows x 4 columns]

## 排列和随机采样

In [110]:
df = DataFrame(np.arange(5*4).reshape(5,4))
sampler = np.random.permutation(5)

In [111]:
sampler

array([1, 0, 2, 3, 4])

In [112]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [113]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [114]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

In [115]:
bag = np.array([5,7,-1,6,4])

In [120]:
sampler = np.random.randint(0,len(bag), size=10)

In [121]:
sampler

array([4, 4, 2, 2, 2, 0, 3, 0, 4, 1])

In [122]:
draws = bag.take(sampler)

In [123]:
draws

array([ 4,  4, -1, -1, -1,  5,  6,  5,  4,  7])

## 计算指标/哑变量

In [124]:
df = DataFrame({'key':['b','b','a','c','a','b'],
               'data1':range(6)})

In [126]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [127]:
df

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [128]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [129]:
df_with_dummy = df[['data1']].join(dummies)

In [130]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [131]:
df.join(dummies)

data1 key  key_a  key_b  key_c
0      0   b      0      1      0
1      1   b      0      1      0
2      2   a      1      0      0
3      3   c      0      0      1
4      4   a      1      0      0
5      5   b      0      1      0

In [132]:
mnames = ['movie_id','title','genres']

In [133]:
movies = pd.read_table('movies.dat', sep='::',
                       header=None,names=mnames)

/home/parallels/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [134]:
movies.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [135]:
genre_iter = (set(x.split('|')) for x in movies.genres)

In [136]:
genre_iter

<generator object <genexpr> at 0x7fbed5613870>

In [137]:
genres = sorted(set.union(*genre_iter))

In [138]:
genres

['Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [139]:
dummies = DataFrame(np.zeros((len(movies), len(genres))), 
                    columns=genres)

In [141]:
for i, gen in enumerate(movies.genres):
    dummies.loc[i, gen.split('|')] = 1

In [150]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.loc[0]

movie_id             title                       genres  Genre_Action  \
0         1  Toy Story (1995)  Animation|Children's|Comedy           0.0   

   Genre_Adventure  Genre_Animation  Genre_Children's  Genre_Comedy  \
0              0.0              1.0               1.0           1.0   

   Genre_Crime  Genre_Documentary      ...        Genre_Fantasy  \
0          0.0                0.0      ...                  0.0   

   Genre_Film-Noir  Genre_Horror  Genre_Musical  Genre_Mystery  Genre_Romance  \
0              0.0           0.0            0.0            0.0            0.0   

   Genre_Sci-Fi  Genre_Thriller  Genre_War  Genre_Western  
0           0.0             0.0        0.0            0.0  

[1 rows x 21 columns]

In [146]:
values = np.random.rand(10)

In [147]:
values

array([0.75603383, 0.90830844, 0.96588737, 0.17373658, 0.87592824,
       0.75415641, 0.163486  , 0.23784062, 0.85564381, 0.58743194])

In [148]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [151]:
pd.cut(values, bins)

[(0.6, 0.8], (0.8, 1.0], (0.8, 1.0], (0.0, 0.2], (0.8, 1.0], (0.6, 0.8], (0.0, 0.2], (0.2, 0.4], (0.8, 1.0], (0.4, 0.6]]
Categories (5, interval[float64]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [149]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           0           1
2           0           0           0           0           1
3           1           0           0           0           0
4           0           0           0           0           1
5           0           0           0           1           0
6           1           0           0           0           0
7           0           1           0           0           0
8           0           0           0           0           1
9           0           0           1           0           0

# 字符串操作

## 字符串对象方法

In [152]:
val = 'a,b, guido'

In [153]:
val.split(',')

['a', 'b', ' guido']

In [154]:
pieces = [x.strip() for x in val.split(',')]

In [155]:
pieces

['a', 'b', 'guido']

In [156]:
first,second,third = pieces

In [157]:
first+'::'+second+'::'+third

'a::b::guido'

In [158]:
'::'.join(pieces)

'a::b::guido'

In [159]:
data = {'Dave':'dave@google.com','Steve':'steve@gmail.com',
       'Rob':'rob@gmail.com','Wes':np.nan}

In [160]:
data = Series(data)

In [161]:
data

Dave     dave@google.com
Rob        rob@gmail.com
Steve    steve@gmail.com
Wes                  NaN
dtype: object

In [162]:
data.isnull()

Dave     False
Rob      False
Steve    False
Wes       True
dtype: bool

In [163]:
data.str.contains('gmail')

Dave     False
Rob       True
Steve     True
Wes        NaN
dtype: object

# 示例:USDA食品数据库

In [165]:
import json
df = json.load(open('ch07/foods-2011-10-03.json'))

In [166]:
len(df)

6636

In [167]:
df[0].keys()

[u'portions',
 u'description',
 u'tags',
 u'nutrients',
 u'group',
 u'id',
 u'manufacturer']

In [168]:
df[0]['nutrients'][0]

{u'description': u'Protein',
 u'group': u'Composition',
 u'units': u'g',
 u'value': 25.18}

In [169]:
nutrients = DataFrame(df[0]['nutrients'])

In [170]:
nutrients.head()

description        group units   value
0                      Protein  Composition     g   25.18
1            Total lipid (fat)  Composition     g   29.20
2  Carbohydrate, by difference  Composition     g    3.06
3                          Ash        Other     g    3.28
4                       Energy       Energy  kcal  376.00

In [171]:
info_keys = ['description','group','id','manufacturer']

In [172]:
info = DataFrame(df, columns=info_keys)

In [173]:
info.head()

description                   group    id  \
0                     Cheese, caraway  Dairy and Egg Products  1008   
1                     Cheese, cheddar  Dairy and Egg Products  1009   
2                        Cheese, edam  Dairy and Egg Products  1018   
3                        Cheese, feta  Dairy and Egg Products  1019   
4  Cheese, mozzarella, part skim milk  Dairy and Egg Products  1028   

  manufacturer  
0               
1               
2               
3               
4

In [174]:
pd.value_counts(info.group)[:5]

Vegetables and Vegetable Products    812
Beef Products                        618
Baked Products                       496
Breakfast Cereals                    403
Legumes and Legume Products          365
Name: group, dtype: int64